export {default as HomeLayout} from './Home'
// export {default as PageLayout} from './Page'
export {default as ProfileLayout} from './profile/Profile'
export {default as ResultsLayout} from './results/Results'
export {default as LoginLayout} from './Login'
