export {default as HomeLayout} from './home/Home'
export {default as ContentLayout} from './Content'
export {default as ProfileLayout} from './profile/Profile'
export {default as EstimationLayout} from './estimation/Estimation'
export {default as LoginLayout} from './Login'
export {default as NotFoundLayout} from './error/404Layout'
