/*===== SALARY ESTIMATION =====*/
export const ADD_USER_SALARY = 'ADD_USER_SALARY'
export const PARSING_MODAL  = 'PARSING_MODAL'
export const SUBSCRIPTION = 'SUBSCRIPTION'
export const PARSING_TEXT = 'PARSING_TEXT'
export const SET_REDIRECT_URL = 'SET_REDIRECT_URL'
export const CV_SENT = 'CV_SENT';
export const PARSING_CV_RESULTS = 'PARSING_CV_RESULTS'

/*===== AUTH =====*/
export const USER_IN_BASE = 'USER_IN_BASE'
export const CLEAR_USER_DATA = 'CLEAR_USER_DATA'
export const ADD_AUTH_DATA = 'ADD_AUTH_DATA'
export const OPEN_LOGIN_MODAL  = 'OPEN_LOGIN_MODAL'
export const ONLY_LOGGED_MODAL  = 'ONLY_LOGGED_MODAL'
export const COOKIES_CONSENT = 'COOKIES_CONSENT'

/*===== REQUEST STATUS =====*/
export const PREDICTIONS_REQUEST_LOADING = 'PREDICTIONS_REQUEST_LOADING'
export const PREDICTIONS_REQUEST_ERRORED = 'PREDICTIONS_REQUEST_ERROR'
export const UPDATE_REQUEST_LOADING = 'UPDATE_REQUEST_LOADING'
export const UPDATE_REQUEST_ERRORED = 'UPDATE_REQUEST_ERRORED'
export const LOADING = 'LOADING'

/*===== UTILS =====*/
export const SET_SORTING = 'SET_SORTING'
export const SET_DISPLAYED_RESULTS = 'SET_DISPLAYED_RESULTS'
export const SET_CURRENCY = 'SET_CURRENCY'
export const GET_CURRENCY_RATES = 'GET_CURRENCY_RATES'
export const SET_PAY_PERIOD = 'SET_PAY_PERIOD'
export const SET_PAY_TAX = 'SET_PAY_TAX'

/*===== CONTENT =====*/
export const ADD_TERMS_CONTENT = 'ADD_TERMS_CONTENT'
export const ADD_COOKIE_POLICY_CONTENT = 'ADD_COOKIE_POLICY_CONTENT'
export const ADD_PRIVACY_POLICY_CONTENT = 'ADD_PRIVACY_POLICY_CONTENT'
export const ADD_MAIN_CONTENT = 'ADD_MAIN_CONTENT'

/*===== ERRORS =====*/
export const PROCESS_FAILED = 'PROCESS_FAILED'
export const SET_ERROR = 'SET_ERROR'