export { default as HomeLayout } from './home/Home'
export { default as ContentLayout } from './ContentLayout'
export { default as ProfileLayout } from './profile/Profile'
export { default as ResumeLayout } from './resume/Resume'
export { default as EstimationLayout } from './estimation/Estimation'
export { default as SigninLayout } from './auth/SigninLayout'
export { default as SignupLayout } from './auth/SignupLayout'
export { default as NotFoundLayout } from './error/404Layout'
export { default as ConfirmEmailLayout } from './confirm-email/ConfirmEmailLayout'

export { default as TestMainLayout } from './test/test-main/TestMainLayout'
export { default as TestQuestionsLayout } from './test/test-questions/TestQuestionsLayout'
export { default as TestResultLayout } from './test/test-result/TestResultLayout'
