export {default as HomeLayout} from './home/Home'
export {default as ContentLayout} from './Content'
export {default as ProfileLayout} from './profile/Profile'
export {default as EstimationLayout} from './estimation/Estimation'
export {default as LoginLayout} from './auth/LoginLayout'
export {default as NotFoundLayout} from './error/404Layout'

export {default as TestMainLayout} from './test/test-main/TestMainLayout'
export {default as TestQuestionsLayout} from './test/test-questions/TestQuestionsLayout'
export {default as TestResultLayout} from './test/test-result/TestResultLayout'
